### ISSUE TITLE
Add "Pomodoro mode"

### ISSUE THREAD

**Issue by igrybkov** [igrybkov/alfred-focus-on-work#49]
## Settings
- [ ] Add ability to set time interval used for Pomodoro session
- [ ] Add ability to set time interval used for a short break
- [ ] Add ability to set time interval used for a long break

## Time intervals
- [ ] Does not show time interval selection since we have time interval already predefined
  - This would require to add a filter between "Choose a task" and "Choose a time" and skip time setting in case a time is set already

## Tasks flow
- [ ] When time is gone, a pomodoro is logged

## Logging
- [ ] Each Pomodoro must be logged somewhere to build a report later
  - Think about where and how you're going to log these pomodoros
- [ ] Build a report
  - How are you going to build report around Pomodoros?
    - Build a PDF with report?
    - Excel?
    - Small web-server and a page?
    - A page in the PDF?
  - What should report contain?
    - Number of pomodoros accomplished
    - What else?

## Related issues

Depends on ability to manipulate with workflow settings (#47)
Pomodoro reminder depends on #1 where reminder functionality should be added
Potentially crosses with task pausing implementation (#48) - at least they should be checked together
